# Generated by Django 2.2.24 on 2023-06-29 16:27
import phonenumbers
from django.db import migrations


def normalize_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = phone_number
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_numbers),
    ]
