# Generated by Django 2.2.24 on 2023-07-10 09:07
import phonenumbers
from django.db import migrations


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if phonenumbers.is_valid_number(phonenumbers.parse(flat.owners_phonenumber, "RU")):
            flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber, move_backward),
    ]
