# Generated by Django 2.2.24 on 2023-07-10 09:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230710_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_flat', models.CharField(max_length=200, verbose_name='ФИО владельца:')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца:')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца:')),
                ('flat', models.ManyToManyField(related_name='owner_flat', to='property.Flat', verbose_name='Квартиры в собсвенности:')),
            ],
        ),
    ]
