# Generated by Django 2.2.24 on 2023-07-20 04:34

from django.db import migrations


def transfer_flats(apps, schema):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.name, owner_pure_phone=owner.pure_phone))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20230713_2016'),
    ]

    operations = [
        migrations.RunPython(transfer_flats),
    ]
